/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab2Staniukynas_Karolis;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import studijosKTU.*;
import java.util.Iterator;
import javax.swing.table.*;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.JButton;
import javax.swing.JFileChooser;
/**
 *
 * @author merp
 */
public class Bendravimas extends javax.swing.JFrame {
           
    
            String duom1=""; 
            ListKTUx<Knygos> duom=new ListKTUx<>(new Knygos());
            ListKTUx<Knygos> kopija=new ListKTUx<>(new Knygos());
            ListKTUx<Knygos> atrinkti=new ListKTUx<>(new Knygos());
            vykdymas vyk=new vykdymas();
            String prad="Pradiniai duomenys:";
            
    /**
     * Creates new form Bendravimas
     */
    public Bendravimas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        Skaityti = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        Pakeisti = new javax.swing.JMenuItem();
        Atrinkti = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Autorius", "Pavadinimas", "Leidykla", "Metai", "Puslapiai", "Kaina"
            }
        ));
        jScrollPane3.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setHeaderValue("Autorius");
            jTable2.getColumnModel().getColumn(2).setHeaderValue("Leidykla");
            jTable2.getColumnModel().getColumn(3).setHeaderValue("Metai");
            jTable2.getColumnModel().getColumn(4).setHeaderValue("Puslapiai");
            jTable2.getColumnModel().getColumn(5).setHeaderValue("Kaina");
        }

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Autorius", "Pavadinimas", "Leidykla", "Metai", "Puslapiai", "Kaina"
            }
        ));
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Autorius");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Leidykla");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Metai");
            jTable1.getColumnModel().getColumn(4).setHeaderValue("Puslapiai");
            jTable1.getColumnModel().getColumn(5).setHeaderValue("Kaina");
        }

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pavadinimas", "Autorius", "Leidykla", "Metai", "Puslapiai", "Kaina"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        jLabel1.setText("Nuo kokios kainos salinti?");

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel2.setText("Autorius");

        jLabel3.setText("Pavadinimas");

        jLabel4.setText("leidykla");

        jLabel5.setText("metai");

        jLabel6.setText("Puslapiai");

        jLabel8.setText("Kaina");

        jLabel7.setText("Tokie Duomenys:");

        jLabel10.setText("Numeris:");

        jTextField8.setText("Kelinta elementa norime pakeist");

        jTextField9.setText("Autorius pagal kuri atrinkti");

        jMenu2.setText("Vykdymas");

        Skaityti.setText("Skaityti");
        Skaityti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SkaitytiActionPerformed(evt);
            }
        });
        jMenu2.add(Skaityti);

        jMenuItem2.setText("Rikiuoti");
        jMenuItem2.setName(""); // NOI18N
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Salinti");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Ar Egzistuoja");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        Pakeisti.setText("Pakeisti");
        Pakeisti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PakeistiActionPerformed(evt);
            }
        });
        jMenu2.add(Pakeisti);

        Atrinkti.setText("Atrinkti");
        Atrinkti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrinktiActionPerformed(evt);
            }
        });
        jMenu2.add(Atrinkti);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Darbas su failais");

        jMenuItem5.setText("Pasirinkite faila");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(448, 448, 448))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(509, 509, 509))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField8)
                                    .addComponent(jTextField9))
                                .addGap(29, 29, 29)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8))
                                        .addGap(28, 28, 28))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField4)
                                    .addComponent(jTextField5)
                                    .addComponent(jTextField6)
                                    .addComponent(jTextField7)
                                    .addComponent(jTextField3)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel7))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel11)))))))
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)))
        );

        jLabel7.getAccessibleContext().setAccessibleName("Tokie duomenys:");

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Skaitymas
 * @param evt 
 */
    private void SkaitytiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SkaitytiActionPerformed
               
                try {
                    // TODO add your handling code here:
                    duom=vyk.Skait(duom1);
                    kopija=duom;
                    
                } catch (IOException ex) {
                    Logger.getLogger(Bendravimas.class.getName()).log(Level.SEVERE, null, ex);
                }
                //DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
                String prad="Pradiniai duomenys:";
                isvest(prad,duom);
//                    Object[] title={prad};
//                    model.addRow(title);
//                for(Knygos b:duom)
//                {
//                    Object[] row={b.getPav(),b.getAut(),b.getLeid(),b.getMetai(),b.getPsl(),b.getKaina()};
//                   
//                    
//                    model.addRow(row);
//                  
//                }
          // System.out.println(duom.size());
           
           
    }//GEN-LAST:event_SkaitytiActionPerformed
/**
 * Rikiavimas
 * @param evt 
 */
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
       // DefaultTableModel modell = (DefaultTableModel) jTable3.getModel();
       // duom.sortBuble();
      duom.sortJava();
        String prad="Surikiuota";
        isvest(prad,duom);
//        Object[] title={prad};
//        modell.addRow(title);
//        
//        for(Knygos b:duom)
//                {
//                    Object[] row={b.getPav(),b.getAut(),b.getLeid(),b.getMetai(),b.getPsl(),b.getKaina()};
//                    modell.addRow(row);
//                    System.out.println();
//                } 
//        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

  /**
   * Salinimas
   * @param evt 
   */ 
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Double kaina=Double.parseDouble(jTextField1.getText());
        vyk.Remove(kaina,duom);
       //  DefaultTableModel modell = (DefaultTableModel) jTable3.getModel();
         String prad="pasalinta";
         isvest(prad,duom);
//          Object[] title={prad};
//          modell.addRow(title);
//           for(Knygos b:duom)
//                {
//                    Object[] row={b.getPav(),b.getAut(),b.getLeid(),b.getMetai(),b.getPsl(),b.getKaina()};
//                    modell.addRow(row);
//                    System.out.println();
//                } 
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed
/**
 * Tikrinimas
 * @param evt 
 */
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        String pav=jTextField2.getText();
        String aut=jTextField3.getText();
        String leid=jTextField4.getText();
        int metai=Integer.parseInt(jTextField5.getText());
        int psl=Integer.parseInt(jTextField6.getText());
        Double kaina=Double.parseDouble(jTextField7.getText());
        Knygos zaid=new Knygos(pav,aut,leid,metai,psl,kaina);
      
        boolean ar=duom.contains(zaid);
       jLabel9.setText( vyk.arYra(ar));
       
   jLabel11.setText(String.valueOf(duom.indexOf(zaid)));
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed
/**
 * Failo parinkimas
 * @param evt 
 */
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        JButton open =new JButton();
        JFileChooser fc=new JFileChooser();
        fc.setCurrentDirectory(new java.io.File("C:\\Users\\merp\\Desktop\\Lab2_BendriniaiSarasai_2016"));
        fc.setDialogTitle("Hello how are you?: Please chose file:");
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        if(fc.showOpenDialog(open)==JFileChooser.APPROVE_OPTION)
                {
                    //
                }
        duom1=fc.getSelectedFile().getAbsolutePath();
        //System.out.println(fc.getSelectedFile().getAbsolutePath());
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed
/**
 * Pakeitimas
 * @param evt 
 */
    private void PakeistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PakeistiActionPerformed
        // TODO add your handling code here:
         String pav=jTextField2.getText();
        String aut=jTextField3.getText();
        String leid=jTextField4.getText();
        int metai=Integer.parseInt(jTextField5.getText());
        int psl=Integer.parseInt(jTextField6.getText());
        Double kaina=Double.parseDouble(jTextField7.getText());
        Knygos zaid=new Knygos(pav,aut,leid,metai,psl,kaina);
        int k=Integer.parseInt(jTextField8.getText());
        duom.set(k, zaid);
         String prad="pakeista";
         isvest(prad,duom);
//         DefaultTableModel modell = (DefaultTableModel) jTable3.getModel();
//          Object[] title={prad};
//          modell.addRow(title);
//           for(Knygos b:duom)
//                {
//                    Object[] row={b.getPav(),b.getAut(),b.getLeid(),b.getMetai(),b.getPsl(),b.getKaina()};
//                    modell.addRow(row);
//                    System.out.println();
//                } 
        
    }//GEN-LAST:event_PakeistiActionPerformed
/**
 * Atranka
 * @param evt 
 */
    private void AtrinktiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrinktiActionPerformed
        // TODO add your handling code here:
        String autorius=jTextField9.getText();
        atrinkti=vyk.Atrinkti(duom,autorius);
        prad="atrinkti";
        isvest(prad,atrinkti);
    }//GEN-LAST:event_AtrinktiActionPerformed
/**
 * Isvedimas
 * @param antraste
 * @param duom 
 */
    public void isvest(String antraste,ListKTUx <Knygos> duom)
    {
        DefaultTableModel modell = (DefaultTableModel) jTable3.getModel();
          Object[] title={antraste};
          modell.addRow(title);
           for(Knygos b:duom)
                {
                    Object[] row={b.getPav(),b.getAut(),b.getLeid(),b.getMetai(),b.getPsl(),b.getKaina()};
                    modell.addRow(row);
                    System.out.println();
                } 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bendravimas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bendravimas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bendravimas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bendravimas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bendravimas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Atrinkti;
    private javax.swing.JMenuItem Pakeisti;
    private javax.swing.JMenuItem Skaityti;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
